### ISSUE TITLE
asahi-6.2-12 FTBFS when rust is enabled on x86

### ISSUE THREAD

**Issue by Conan-Kudo** [AsahiLinux/linux#143]
I noticed with Fedora builds of the kernel that the `asahi-6.2-12` patchset fails to build on x86_64 when rust is enabled.

The error during compilation is this:

```
rust/helpers.c: In function 'rust_helper_of_node_is_root':
rust/helpers.c:337:16: error: implicit declaration of function 'of_node_is_root'; did you mean 'of_node_is_type'? [-Werror=implicit-function-declaration]
  337 |         return of_node_is_root(np);
      |                ^~~~~~~~~~~~~~~
      |                of_node_is_type
cc1: some warnings being treated as errors
```

Which seems to be caused by fee006dce0b53be6fc0e92e334a4ec7d07f0a8ba ("rust: of: Add OF node abstraction" by @asahilina) not being guarded properly when `CONFIG_OF` is not enabled.

This obviously doesn't matter _directly_ for Asahi Linux, but is necessary for upstreaming, and I certainly would like to be able to build Fedora kernels with Rust enabled on all arches (as will be required when I upstream enabling Rust in the Fedora kernel).

I would appreciate it if it could be fixed in the next patch set respin.

**Comment by Conan-Kudo** [comment]
Additional notes:

My kernel tree (with the patch set applied): https://gitlab.com/fedora-asahi/kernel-asahi/-/commits/kernel-6.2.14-450.asahi?ref_type=tags

The commit there: https://gitlab.com/fedora-asahi/kernel-asahi/-/commit/154a3cb3d7c19b57b7b677faf16a5cd67842e053

Copr build logs: https://copr.fedorainfracloud.org/coprs/g/asahi/kernel-edge/build/5895108/

**Comment by Conan-Kudo** [comment]
This has been resolved in the `asahi-6.5-29` patch set with the combination of these three commits:

* https://github.com/AsahiLinux/linux/commit/ab244f0c46c0fc86ecd10840a029f52b7d4fac94
* https://github.com/AsahiLinux/linux/commit/214ec2d84fe88bafad29f38d74707c4a3e45af8b
* https://github.com/AsahiLinux/linux/commit/1e02bd56f11c6ef6b8feaf103539686a4bbaff4f
